var countryList=[
{shop:"Sethani",address:"Ratanpolenaka,Relifroad,north-east-desc:cloths"},
{shop:"Sakhi Selection",address:"RatanpoleNaka,Relifroad-Desc:"},
{shop:"Sahiyar",address:"RatanpoleNaka,relifroad,east-Desc:------- "},
{shop:"Real Silk Palace",address:"RatanpoleNaka,Relifroad-Desc:"},
{shop:"Manglik",address:"RatanpoleNaka,Relifroad,disc:------(-"},
{shop:"Yadgaar Enterprise",address:"RatanpoleNaka,Relifroad-Desc:"},
{shop:"Rami Mahendrabhai Sardaben",address:"RatanpoleNaka,Relifroad-Desc:flowers"},
{shop:"Rajnikant",address:"RatanpoleNaka,Relifroad-Desc:HolsaleCloths"},
{shop:"Ever New",address:"Near:Ratanpolenaka,NorthE,Relifroad-desc:"},
{shop:"Rajvadi",address:"Near:Ratanpolenaka,NorthE,Relifroad-desc:"},
{shop:"Manmelap",address:"Near:Ratanpolenaka,NorthE,Near:Nagorishala-Desc:sari"},
{shop:"Angna",address:"Near:Ratanpolenaka,NorthE,Near:Nagorishala-Desc:Sari"},
{shop:"New Life",address:"Near:Ratanpolenaka,Opp:Nagorishala-Desc:cloths"},
{shop:"Aakruti",address:"nearzaverivaad,opp:nagorishala-desc:cloths"},
{shop:"Asopalav",address:"opp:nagorishala,zaverivadnaka-desc:saries"},
{shop:"Vaibhav",address:"opp:nagorishala,opp:zaverivaad-policechawky-disc:saris&dresses"},
{shop:"Nobels",address:"near:zaverivad,opp:nagorishala-desc:BombayDyeing,bed,bath,cloths"},
{shop:"Right Choice",address:"near:zaverivadnaka,opp:zaverivad-police-chawky-disc:readymade,ladis"},
{shop:"Odhani",address:"Near:Zaverivadnaka,Opp:Piplapole-disc:Sari"},
{shop:"Paridhan",address:"Near:Zaverivadnaka,Opp:Piplapole-disc:Readymade-Jents,"},
{shop:"Padmavati",address:"Near:Zaverivadnaka,Opp:Piplapole-disc:Children"},
{shop:"Palace",address:"Near:Zaverivadnaka,Opp:Piplapole-disc:Sari"},
{shop:"Amisagar",address:"Near:Zaverivadnaka,Opp:Piplapole-disc:Sari"},
{shop:"Tirth FashonHouse",address:"Near:Zaverivadnaka,Opp:Piplapole-disc:Bangles,Neckles"},
{shop:"Kanku Pagla",address:"Near:Zaverivadnaka,Opp:Piplapole-disc:Sari"},
{shop:"Raj Creation",address:"Aamblipol,Opp:Piplapole-disc:"},
{shop:"Raj Dulari",address:"Aamblipol,Opp:Piplapole-disc:"},
{shop:"Raja Rani",address:"Aamblipol,Opp:Piplapole-disc:"},
{shop:"Utsav",address:"Near:Zaverivadnaka,Opp:Piplapole-disc:Sari"},
{shop:"Ratnamani-selection",address:"Near:Aamblipole,Opp:Piplapole-disc:Readymade,Servani,"},
{shop:"Pradip Stors",address:"Near:Aamblipole,Opp:Piplapole-disc:sari"},
{shop:"Shah Popatlal Chandulal",address:"Near:Aamblipole,Opp:Piplapole-disc:sari"},
{shop:"Sriman Srimati",address:"Near:Aamblipole,Opp:Piplapole-disc:Saris"},
{shop:"Jay Mataji",address:"Near:Aamblipole,Opp:Piplapole-disc:Children"},
{shop:"Aangi",address:"Near:Navgharinudelu,opp:Golvad-disc:Sari"},
{shop:"Sajni",address:"Near:Navgharinudelu,opp:Golvad-disc:Redymade-Dress"},
{shop:"Sanvari",address:"Near:Navgharinudelu,opp:Golvad-disc:Sari"},
{shop:"Chamunda Dresses",address:"Navgharinudelu,opp:Golvad-disc:Children"},
{shop:"Alite",address:"NavghariNuDelu,Opp:Golvad,disc:JentsReadymade"},
{shop:"Aagam",address:"Near:Navgharinudelu,opp:Golvad-desc:---------"},
{shop:"Patrani",address:"Near:Navgharinudelu,opp:Golvad-disc:Sari"},
{shop:"Shilpa-fashon",address:"Near:Navgharinudelu,opp:Golvad-desc:Ladis"},
{shop:"AanganNX",address:"Near:Navgharinudelu,opp:Golvad-disc:"},
{shop:"Fairy Girl",address:"Near:Agarvalnikhadki,OppGolvad-disc:sari"},
{shop:"Radhe Trading Co.",address:"Near:Agarvalnikhadki,OppGolvad-desc:sari"},
{shop:"Devshri",address:"Near:Agarvalnikhadki,OppGolvad-desc:sari"},
{shop:"Fashion Fair",address:"Near:Agarvalnikhadki,OppGolvad-desc:Ladis"},
{shop:"Adani Sons",address:"Near:Agarvalnikhadki,OppGolvad-desc:"},
{shop:"Panghat",address:"AgarvalNiKhadki,Opp:Golvad-desc:Ladis"},
{shop:"Kajal Silk Palace",address:"Near:Agarvalnikhadki,OppGolvad-desc:"},
{shop:"Najranu",address:"Near:Agarvalnikhadki,OppGolvad-desc:"},
{shop:"Sanskruti",address:"Near:Agarvalnikhadki,OppGolvad-desc:"},
{shop:"RadheKrisna Selection",address:"Near:Agarvalnikhadki,OppGolvad-desc"},
{shop:"Raja Rani",address:"Near:Agarvalnikhadki,OppGolvad-desc:"},
{shop:"Palav",address:"Near:Agarvalnikhadki,OppGolvad-desc:"},
{shop:"Lajvanti",address:"Near:Agarvalnikhadki,OppGolvad-desc:"},
{shop:"Kumkum",address:"Near:AgarvalNiKhadki,Opp:FatebhaiNiHaveli-desc:"},
{shop:"Bombay Chudighar",address:"Opp:FatebhaiNiHaveli,Near:AgarvalNiKhadki-desc:Bangles"},
{shop:"Shree Kalyani",address:"Opp:FatebhaiNiHaveli,Near:AgarvalNiKhadki-desc:"},
{shop:"Amikunj",address:"Opp:FatebhaiNiHaveli,Near:AgarvalNiKhadki-desc:"},
{shop:"SanskrutiNX",address:"Opp:FatebhaiNiHaveli,Near:AgarvalNiKhadki-desc:"},
{shop:"Raj Gharana",address:"Opp:Fatebhainihaveli,,Near:AgarvalNiKhadki-desc:Readymade"},
{shop:"Shree Radhe",address:"Opp:FatebhaiNiHaveli,Near:Vaghanpole-desc:Sari"},
{shop:"Nareshchandra & co.",address:"OppFatebhaiNiHaveli,Near:Vaghanpole-desc:"},
{shop:"Riddhi",address:"Opp:FatebhaiNiHaveli,Near:AgarvalNiKhadki"},
{shop:"Shree KastbhanjanDev",address:"Opp:FatebhaiNiHaveli,Near:Agarvalnikhadki-desc:"},
{shop:"Gulabdas & co.",address:"Vaghanpolenaka,opp:Hathikhana-desc:Children"},
{shop:"SubhMangalya",address:"Vaghanpolenaka,opp:Hathikhana-desc:Sari"},
{shop:"Toran",address:"Vaghanpolenaka,opp:Hathikhana-desc:Sari"},
{shop:"Sarita",address:"Vaghanpolenaka,opp:Hathikhana-desc:Sari"},
{shop:"Devikrupa",address:"Vaghanpolenaka,opp:Hathikhana-desc:Sari"},
{shop:"Rupvadhu",address:"Vaghanpolenaka,opp:Hathikhana-desc:Sari"},
{shop:"R Prabhudas Limbdiwala",address:"Vaghanpolenaka,opp:Hathikhana-desc:Cloths"},

{shop:"Kiran stors",address:"Vaghanpolenaka,opp:Hathikhana-desc:blouse"},
{shop:"Kanyadaan",address:"Ff,Vaghanpolenaka,Opp:Hathikhana-desc:Sari-chaniyacholi"},
{shop:"Shah Fulchand Dahyabhai",address:"Vaghanpolenaka,Opp:Hathikhana-desc:sari"},
{shop:"Joban",address:"Near:Vaghanpole,Opp:Sethnipole-desc:Bangles"},
{shop:"Sucan Silk Palace",address:"Vaghanpolenaka,Opp:sethnipole-desc:Saris"},
{shop:"Apsara Sadi Kendra",address:"Near:Balelihaveli,Opp:Sethnipole-desc:Saris"},
{shop:"Puspkala",address:"Near:Balelihaveli,Opp:Sethnipole-desc:saris"},
{shop:"Arihant-NX",address:"Near:Balelihaveli,Opp:Sethnipole-desc:Readymade-ladis"},
{shop:"Dulhan Saris",address:"Near:Balelihaveli,Opp:Sethnipole-desc:Saris"},
{shop:"Active",address:"Near:Balelihaveli,Opp:Sethnipole-desc:Saris"},
{shop:"Mansi Silk Palace",address:"Near:Balelihaveli,Opp:Sethnipole-desc:Saris"},
{shop:"Kalash",address:"Near:Balelihaveli,Opp:Sethnipole-desc:Saris"},
{shop:"Favourit",address:"Near:Balelihaveli,Opp:Sethnipole-desc:Saris"},
{shop:"Ma krupa Saris",address:"Near:Balelihaveli,Opp:Sethnipole-desc:Saris"},
{shop:"Kesar CreationNX",address:"Near:Marchipole,Opp:Sethnipole-desc:"},
{shop:"Shah Pravinchandra Danmal",address:"Near:Marchipole,Opp:Sethnipole-desc:"},
{shop:"Derani Jethani",address:"Near:Marchipol,Opp:Sethnipole-desc:"},
{shop:"P K Shah",address:"Near:Marchipole,Opp:Sethnipole-desc:"},
{shop:"Sha Santilal Bhaichand",address:"Near:Marchipole,Opp:Sethnipole-desc:"},
{shop:"Kamlesh Stors",address:"Marchipolenaka,Opp:Sethnipole-desc"},
{shop:"Pramanik Maching Center",address:"Near:Marchipole,Opp:Sethnipole-desc:ladis"},
{shop:"Up To Date Silk Palace",address:"Near:Marchipole,Opp:Sethnipole-desc:"},
{shop:"Bafta Silk Palace",address:"Near:Marchipole,Opp:Sethnipole-desc:"},
{shop:"N Ratilal",address:"Near:Marchipole,Opp:Sethnipole-desc:"},
{shop:"Chhotalal Hirachand Shah",address:"Btwn:Marchipole&Naginapole-desc:"},
{shop:"Mangalam",address:"Btwn:Marchipole&Naginapole-desc:"},
{shop:"Shah Ambalal Keshavlal",address:"Btwn:Marchipole&Naginapole-desc:"},
{shop:"Shubhvivah",address:"Btwn:Marchipole&Naginapole-desc:"},
{shop:"Rutvi",address:"Btwn:Marchipole&Naginapole-desc:"},
{shop:"Lilapaan",address:"Btwn:Marchipole&Naginapole-desc:"},
{shop:"Akshara",address:"Btwn:Marchipole&Naginapole-desc:"},
{shop:"Vastaram",address:"Naginapole,Opp:Limbupole-desc:"},
{shop:"Jyoti Stors",address:"Naginapole,Opp:Limbupole-desc"},
{shop:"Deepavali",address:"Naginapole,Opp:Limbupole-desc"},
{shop:"Krishna CholiSet",address:"NaginapoleOpp:Limbupole-desc:"},
{shop:"Mehta Jwlers",address:"Naginapole,Opp:Limbupole-desc"},
{shop:"Panchal Chunilal Parsotamdas",address:"Naginapole,OppLimbupole-desc"},
{shop:"Bhikhalal Bhogilal Patel&co.",address:"Near:Naginapole,Opp:Limbupole-desc:"},
{shop:"Sarad Punam",address:"Near:Naginapole,Opp:Limbupole-desc"},
{shop:"Vinodbhai C Shah&co.",address:"Near:Naginapole,Opp:Limbupole-desc"},
{shop:"Zaveri & co.",address:"Opp:Lumbupole,Near:Gandhiroad-desc:closed"},
{shop:"Patel Vasudev Narotamdas&co.",address:"nearNagoripole,opp:Limbupole-desc:"},
{shop:"Arpy Jwelars",address:"Near:Naginapole,OppLimbupole-desc"},
{shop:"Dalsukhram Gordhandas Panchal",address:"Near:Naginapole,Opp:Limbupole-desc"},
{shop:"Harsad PanHouse",address:"Gandhiroad,Ratanpolenaka-desc:PanNoGallo"},
{shop:"Kalkatta Novelty",address:"Near:Limbupole,Gandhiroad-desc:Mukhvas"},
{shop:"P C Sony&co.",address:"Near:Limbupole,Gandhiroad-desc:"},
{shop:"Khodidas Dalichand Paalajwala",address:"Near:Limbupole,Gandhiroad-desc:"},
{shop:"Patle Ambalal SomnathSarkarJwelars",address:"Near:Limbupole,Opp:Naginapole-desc:"},
{shop:"Rahul(EmitesonJwelary)",address:"Near:Limbupole,Opp:Naginapole-desc:"},
{shop:"V C Designer(VinodbhaiCShah)",address:"Near:Limbupole,Opp:Naginapole-desc:"},
{shop:"Soni Damodardas Mohanlal&sons",address:"Near:Limbupole,Opp:Naginapole-desc"},
{shop:"Keron Fashion",address:"Near:Limbupole,Opp:Naginapole-desc:"},
{shop:"New Roopa Fashions",address:"Opp:Btwn:Marchipole&Naginapole-desc"},
{shop:"Soni Ashvinkumar Mansukhlal",address:"Opp:Btwn:Marchipole&Naginapole-desc"},
{shop:"Aaradhya Designer",address:"Opp:Btwn:Marchipole&Naginapole-desc"},
{shop:"Anjana",address:"Opp:Btwn:Marchipole&Naginapole-desc"},
{shop:"Ever Green",address:"Opp:Btwn:Marchipole&Naginapole-desc:"},
{shop:"Jigar Govindbhai Choksi",address:"Opp:Btwn:Marchipole&Naginapole-desc:"},
{shop:"Shree Shakti",address:"Opp:Btwn:Marchipole&Naginapole-desc:"},
{shop:"Shah Popatlal Kalidas",address:"Opp:Btwn:Marchipole&Naginapole-desc"},
{shop:"Patel Natvarlal Chinubhai",address:"Opp:Btwn:Marchipole&Naginapole-desc:"},
{shop:"Kaamdhenu Saris",address:"Opp:Btwn:Marchipole&Naginapole-desc:"},
{shop:"Shah Babulal Amulakhdas",address:"Opp:Btwn:Marchipole&Naginapole-desc:"},
{shop:"Abhinetri",address:"Opp:Btwn:Marchipole&Naginapole-desc:"},
{shop:"Aayushi Saris",address:"Opp:Btwn:Marchipole&Naginapole-desc:"},
{shop:"Happy",address:"Near:Sethnipole,Opp:Marchipole-desc:"},
{shop:"Rani Shahiba",address:"Near:Sethnipole,Opp:Marchipole-desc"},
{shop:"Bhupendra Stores",address:"Near:Sethnipole,Opp:Marchipole-desc"},
{shop:"Shree Subh",address:"Near:Sethnipole,Opp:Marchipole-desc"},
{shop:"Shree Ambika",address:"Near:Sethnipole,Opp:Marchipole-desc:"},
{shop:"Ratnamala Saris(Ognajwala)",address:"Near:Sethnipole,Opp:Marchipole-desc"},
{shop:"B Durghaiya",address:"Near:Sethnipole,Opp:Marchipole-desc:"},
{shop:"Mahalakshmi(easanpurvala)",address:"Near:Sethnipole,Opp:Marchipole-desc:"},
{shop:"Kantilal Parsotamdas",address:"Near:Sethnipole,Opp:Blelihaveli-desc:"},
{shop:"Anjali Fashion",address:"Near:Sethnipole,Opp:Blelihaveli-desc:"},
{shop:"7star-plus",address:"near:sethnipole,opp:balelihaveli,disc:radimade garments"},
{shop:"7star",address:"near:sethnipole,opp:balelihaveli-desc:readymade,kurti,salvar"},
{shop:"Kankavati",address:"Ff,near:sethnipole,opp:balelihaveli-desc:saris"},
{shop:"Shivam",address:"near:sethnipole,opp:BaleliHaveli-desc:Bengles"},
{shop:"Aone",address:"Near:SethniPole,Opp:Balelihaveli-desc:Bengles"},
{shop:"Rajlakshmi",address:"Near:Sethnipole,Opp:Balelihaveli-desc:Sari"},
{shop:"Saheli",address:"Opp:Vaghanpole,Near:Sethnipole-desc:Sari"},
{shop:"Jaliyan",address:"Near:Sethnipole,Opp:Vaghanpole-desc:Readymade"},
{shop:"Akshay Prabhudas Limbdivala",address:"Opp:Vaghanpole,Near:hathikhananaka-desc:cloths"},
{shop:"Venus & co.",address:"opp:vaghanpole,near:hathikhana-description:JentsTailor"},
{shop:"Jay Mataji",address:"Opp:Vaghanpole,Hathikhananaka-desc:ChildrenwareReadymade"},
{shop:"Avsar",address:"Hathikhananaka,Opp:Vaghanpole,Ff-desc:Sari"},
{shop:"Adani",address:"Hathikhananaka,Opp:Vaghanpole-desc:cloths"},
{shop:"Shah Chandulal Babulal&co.",address:"Hathikhananaka,Opp:Vaghanpole-desc:Readymade,Jents"},
{shop:"Always",address:"Hathikhananaka,Opp:Vaghanpole-desc:"},
{shop:"Abhinetri Saris",address:"Hathikhananaka,Opp:Vaghanpole-desc:sari"},
{shop:"Gohel Brothers",address:"Hathikhananaka,Opp:Vaghanpole-desc:children"},
{shop:"Deeprekha",address:"Near:Hathikha,Opp:Vaghanpole-desc:Closed"},
{shop:"Ever Glade",address:"Near:Hathikha,Opp:Vaghanpole-desc:Cloths"},
{shop:"Roop Palace",address:"Btwn:FatebhaiNiHaveli&Hathikhana-desc"},
{shop:"Vaishali",address:"Btwn:FatebhaiNiHaveli&Hathikhana-desc"},
{shop:"Rasam",address:"Btwn:FatebhaiNiHaveli&Hathikhana-desc"},
{shop:"Kshemkari Dresses",address:"Btwn:FatebhaiNiHaveli&Hathikhana-desc"},
{shop:"Rajeshvar",address:"Btwn:FatebhaiNiHaveli&Hathikhana-desc"},
{shop:"Ever Shine",address:"Btwn:FatebhaiNiHaveli&Hathikhana-desc"},
{shop:"Astmangal",address:"Btwn:FatebhaiNiHaveli&Hathikhana-desc"},
{shop:"Sangam FashionWare",address:"Btwn:FatebhaiNiHaveli&Hathikhana-desc:"},
{shop:"Jay Ambe Selection",address:"Fatebhainihaveli,Near:CJMarket-desc:"},
{shop:"New Style",address:"FatebhaiNiHaveli,Near:CJMarket-desc:"},
{shop:"Maitri",address:"Near:FatebhaiNiHaveli,Near:CJMarket-desc:"},
{shop:"Hetashvi",address:"Near:FatebhaiNiHaveli,Near:CJMarket-desc:"},
{shop:"Shiromani Designer",address:"Near:FatebhaiNiHaveli,Near:CJMarket-desc:"},
{shop:"Nayra",address:"Near:FatebhaiNiHaveli,Near:CJMarket-desc:"},
{shop:"Maniti",address:"Near:FatebhaiNiHaveli,Near:CJMarket-desc:"},
{shop:"Aone Silk Palace",address:"CJMarket,Near:FatebhaiNiHaveli-desc:"},
{shop:"Bandhan",address:"CJMarket,Near:FatebhaiNiHaveli-desc:"},
{shop:"RatnamaniNX",address:"CJMarket,Near:FatebhaiNiHaveli-desc:"},
{shop:"Kamal Stors",address:"CJMarket,Near:FatebhaiNiHaveli-desc:"},
{shop:"Kalpna Creation",address:"CJMarket,Near:FatebhaiNiHaveli-desc:"},
{shop:"Rajshree",address:"Near:FatebhaiNiHaveli,Near:CJMarket-desc:"},
{shop:"Rajvi",address:"Near:FatebhaiNiHaveli,Near:CJMarket-desc:"},
{shop:"Swayamvar",address:"Near:Golvad,Opp:NavghariNuDelu-desc:Sari"},
{shop:"A-Green",address:"Near:Golvad,Opp:NavghariNuDelu-desc:"},
{shop:"Ma Krupa",address:"Near:Golvad,OppNavghariNuDelu-desc:"},
{shop:"Sonali Creation",address:"Near:Golvad,Opp:NavghariNuDelu-desc:"},
{shop:"RatnamaniNX",address:"Near:Golvad,Opp:NavghariNuDelu-desc:Sari&dress"},
{shop:"Gajjar Process Studio", address:"Near:Golvad,Opp:NavghariNuDelu-desc:"},
{shop:"Kalyani Saris",address:"Near:Golvad,Opp:NavghariNuDelu-desc:Sari"},
{shop:"Ajanta Stors",address:"Near:Golvad,Opp:AgarvalNiKhadki-desc:"},
{shop:"Hastmelap",address:"Near:Golvad,Opp:NavghariNuDelu-desc:Sari"},
{shop:"Alite",address:"Near:Golvad,Opp:NavghariNuDelu-desc:Readymade-Jents"},
{shop:"Kanubhai B Shah",address:"Near:Golvad,Opp:Navgharinudelu-desc"},
{shop:"Rajwada Dulha Colection",address:"Near:Golvad,Opp:Navgharinudelu-desc:"},
{shop:"Om Selection",address:"Near:Golvad,Opp:Navgharinudelu-desc"},
{shop:"Khoobsurst",address:"Near:Piplapole,Opp:Aamblipole-desc"},
{shop:"MangalyaNX",address:"Near:Piplapole,Opp:Aamblipole-desc:"},
{shop:"Deepkala",address:"Near:Piplapole,Opp:Aamblipole-desc:"},
{shop:"Doli Selection",address:"Near:Piplapole,Opp:Aamblipole-desc"},
{shop:"Rejency",address:"Piplapole,Opp:Aamblipole-desc:"},
{shop:"Anuroop",address:"Piplapole,Opp:Aamblipole-desc"},
{shop:"Mahi Fashion",address:"Piplapole,Opp:Aamblipole-desc:"},
{shop:"My Pleasure",address:"Piplapole,Opp:Aamblipole-desc:"},
{shop:"Panchratna",address:"Piplapole,Opp:Aamblipole-desc:"},
{shop:"Aashish",address:"Piplapole,Opp:Aamblipole-desc:"},
{shop:"Paaras",address:"Piplapole,Opp:Aamblipole,desc:--"},
{shop:"Jay Ambe Selection",address:"Piplapole,Opp:Aamblipole-desc:"},
{shop:"Aarvi Fashion",address:"Near:Piplapole,Opp:Zaverivad-desc"},
{shop:"ShreeMangalam",address:"Near:Piplapole,Opp:Zaverivad-desc"},
{shop:"SaiKrishna",address:"Near:Piplapole,Opp:Zaverivad-desc:"},
{shop:"Folds",address:"Near:Piplapole,Opp:Zaverivad-desc:"},
{shop:"Ramdev Fashion",address:"Near:Piplapole,Opp:Zaverivad-desc:"},
{shop:"No Name",address:"Near:Nagorishala,Opp:Zaverivad-desc"},
{shop:"Vasant",address:"Near:Nagorishala,Opp:Zaverivad-desc:ReadymadeChildren"},
{shop:"Kembe",address:"Near:Nagorishala,Opp:Zaverivad-desc"},
{shop:"Mayra",address:"Near:Nagorishala,Opp:Zaverivad-desc"},
{shop:"Priyadarshan",address:"Near:Nagorishala,Opp:Zaverivad-desc:Cloths"},
{shop:"Ruprani",address:"Near:Nagorishala,Opp:Zaverivad-desc"},
{shop:"Sangini",address:"Near:Nagorishala,Opp:Zaverivad-desc"},
{shop:"Yuvrani",address:"Near:Nagorishala,Opp:Zaverivad-desc"},
{shop:"Anokhi",address:"Near:Nagorishala,Opp:Zaverivad-desc"},
{shop:"Paneri",address:"Near:Nagorishala,Opp:Zaverivad-desc:"},
{shop:"Surbhi",address:"Nagorishala,Near:Zaverivad Police Chowkey-desc:dresses"},
{shop:"Shree Surbhi",address:"Nagorishala,Near:Zaverivad Police Chowkey-desc:dresses"},
{shop:"Sukanya Junction",address:"Nagorishala,Near:Zaverivad Police Chowkey-desc:"},
{shop:"ShreeSangam",address:"Nagorishala,Near:Zaverivad Police Chowkey-desc:"},
{shop:"Raj Angana",address:"Nagorishala,Near:Zaverivad Police Chowkey-desc:"},
{shop:"Khushi Dresses",address:"Nagorishala,Near:ZaverivadPoliceChowkey-desc:"},
{shop:"S R Creation",address:"Nagorishala,Near:Zaverivad Police Chowkey-desc:"},
{shop:"Piyoo",address:"Near:Nagorishala,NorthWest,opp:zaverivad,Disc:coffee,juce"},
{shop:"Janta Bharat Store",address:"Near:Nagorishala,North-West-desc:Underware,baniyaan"},
{shop:"Tapovan",address:":Nagorishala,NorthWest,desc:Sari--"},
{shop:"DLax",address:"Near:Nagorishala,NorthWest-desc:sari"},
{shop:"Kanter",address:"Between:relifroad&Nagorishala,NorthWest-desc:Sari"},
{shop:"Manpasand",address:"Between:relifroad&Nagorishala,NorthWest-desc:Sari"},
{shop:"Om Selection",address:"Between:relifroad&Nagorishala,NorthWest-desc:sari"},
{shop:"Venus",address:"Between:relifroad&Nagorishala,NorthWest-desc:sari"},
{shop:"Anon",address:"Between:relifroad&Nagorishala,NorthWest-desc:cloths"},
{shop:"Honest",address:"Between:relifroad&Nagorishala,NorthWest-desc:cloths"},
{shop:"Aashirvad",address:"Between:relifroad&Nagorishala,NorthWest-desc:"},
{shop:"Honour Garment",address:"Near:Nagorishala,North West-desc:Readymade "},
{shop:"Sethsons",address:"Near:Ratanpolenaka,North West,Relifroad-desc:cloths"},
{shop:"Mangalya",address:"Near:Ratanpolenaka,North West,Relifroad-desc:cloths"},
{shop:"Ratnaraj",address:"Near:Ratanpolenaka,North West,Relifroad-desc:cloths"},
{shop:"Sukanya",address:"Near:Ratanpolenaka,NorthWest,Relifroad-desc:Sari"},
{shop:"Aashika",address:"Near:Ratanpolenaka,NorthWest,Relifroad-desc:dresses"},
{shop:"Aarohi",address:"Near:Ratanpolenaka,NorthWest,Relifroad-desc:dresses"},
{shop:"Aashapura Cover House",address:"Near:Ratanpolenaka,North-West,Relifroad-desc:MobileAssessoris"},
{shop:"Vinayak Cover House",address:"Near:Ratanpolenaka,North-West,Relifroad-desc:MobileAssesories"}
];
let icon= document.querySelector('.icon');
let menu= document.querySelector('.menu');
let searchResults= document.querySelector('.results');
let searchBox=document.querySelector('input');
let selectedCountry = document.querySelector('.selected');
let selected_country = document.querySelector('.displayKhand');
icon.onclick = function(){
    icon.classList.toggle('open');
    menu.classList.toggle('open');
};
countryList.forEach((country)=>{
    let li=`<li>${country.shop+" "+country.address}</li>`;
    searchResults.innerHTML+=li;
});
searchBox.addEventListener('keyup',()=>{
    searchResults.scrollTop = 0;
    let resultOfSearch = countryList.filter((country)=>{
        return country.shop.startsWith(searchBox.value.trim());
    });
    searchResults.innerHTML='';
    for (let i =0; i<resultOfSearch.length; i++){
        searchResults.innerHTML += `<li>${resultOfSearch[i].shop+" "+resultOfSearch[i].address}</li>`;
    };
});
searchResults.addEventListener('click',(e)=>{
    if (e.target.tagName = 'li'){
        searchResults.innerHTML = '';
        for (let j=0;j<countryList.length;j++){
            searchResults.innerHTML+= `<li>${countryList[j].shop+" "+countryList[j].address}</li>`;
            };
           // selectedCountry.innerHTML=e.target.innerHTML;
            selected_country.innerHTML = e.target.innerHTML;
            searchBox.value = '';
            menu.classList.remove('open');
            icon.classList.remove('open');
        };
});